#!/bin/bash

# TODO: Install some packages with --asdeps?
# TODO: Install jq
# TODO: install polkit pkgfile

# ROOT=$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")

COMMANDS=( config_alacritty
           config_bash
           config_emacs
           config_firefox
           config_git
           config_git_go
           config_git_rust
           config_sway
           initial
           install_emacs
           install_fonts
           install_packages
           install_rust
           install_sway
           install_tools
           install_x
         )

# out() { printf "$1 $2\n" "${@:3}"; }
out() { printf "%s %s\n" "$1" "$2"; }
error() { out "==> ERROR:" "$@"; } >&2
die() { error "$@"; exit 1; }

usage() {
    out "Usage: $0 <commands>"
    out
    out "Commands:"
    for c in "${COMMANDS[@]}" ; do
        out '  ' "$c"
    done
}

config_alacritty() {
    rm -rf ~/.config/alacritty
    mkdir -p ~/.config/alacritty
    cp "$HOME/dotFiles/alacritty/alacritty.toml" ~/.config/alacritty/
}

config_bash() {
    # direnv: https://direnv.net/docs/hook.html

    cat >>~/.bashrc <<EOF

# BEGIN config_bash
source $HOME/dotFiles/shell/aliases.sh
export PATH=\$PATH:$HOME/dotFiles/wannabin
export PATH=\$PATH:$HOME/local/bin
export PATH=\$PATH:$HOME/.cargo/bin
export PATH=\$PATH:$HOME/go/bin

export EDITOR=emacs
export TERMINAL=alacritty

eval "\$(fasd --init auto)"
eval "\$(direnv hook bash)"
# END config_bash
EOF
}

config_emacs() {
    INIT="$HOME/dotFiles/emacs/d-init.el"
    echo "(load \"$INIT\")" > ~/.emacs
}

config_firefox() {
    python firefox.py
}

config_git() {
    git config --global init.defaultBranch master
    git config --global pull.rebase true
    git config --global user.email "yordanm@proton.me"
    git config --global user.name "Yordan Miladinov"
}

config_git_go() {
    git config --global url.git@github.com:.insteadOf https://github.com/
}

config_git_rust() {
    git config --global --remove-section "url.git@github.com:"
}

config_sway() {
    SWAY="$HOME/.config/sway"

    # Make a backup
    if [ -d "$SWAY" ] ; then
        BACKUP=$HOME/.config/sway.backup
        rm -rf "$BACKUP"
        cp -r "$SWAY" "$BACKUP"
    fi

    # Make sure ~/.config/sway exists.
    mkdir -p "$SWAY"

    # Copy example config.
    cp -f /etc/sway/config "$SWAY/"

    # Make it load additional config files.
    echo "include $HOME/.config/sway/*.conf" >> "$SWAY/config"

    # Copy additional config files.
    cp -t "$SWAY" "$HOME/dotFiles"/sway/*.conf # fix the star

    # TODO: Check ctrl:swapcaps
}

initial() {
    cat <<EOF
[0] After arch-chroot:

    # pacman -S dhcpcd git iwd sudo vi


[1] On freshly installed system:

    # echo '%wheel ALL=(ALL:ALL) NOPASSWD: ALL' >/etc/sudoers.d/custom
    # chmod 0440 /etc/sudoers.d/custom

    # useradd -m -G wheel,input -s /bin/bash d


[2] As user:

    $ ssh-keygen -t rsa -b 4096 -C 'yordanm@proton.me'
EOF
}

_install_aur() {
    local package="$1"

    mkdir -p ~/local/aur
    (
        cd ~/local/aur || die
        local url="https://aur.archlinux.org/cgit/aur.git/snapshot/${package}.tar.gz"
        curl -O "$url" || die "curl: failed to fetch $url"
        tar xf "${package}.tar.gz"
        (
            cd "$package" || die
            makepkg -is --noconfirm
        )
    )
}

install_emacs() {
    # Install dependencies of emacs
    sudo pacman -Sy --noconfirm --overwrite '*' --asdeps \
           acl                                           \
           alsa-lib                                      \
           dbus                                          \
           fontconfig                                    \
           freetype2                                     \
           gdk-pixbuf2                                   \
           giflib                                        \
           glib2                                         \
           gmp                                           \
           gnutls                                        \
           gpm                                           \
           gtk3                                          \
           harfbuzz                                      \
           jansson                                       \
           lcms2                                         \
           libgccjit                                     \
           libice                                        \
           libjpeg-turbo                                 \
           libotf                                        \
           libpng                                        \
           librsvg                                       \
           libsm                                         \
           libtiff                                       \
           libxfixes                                     \
           libxml2                                       \
           m17n-lib                                      \
           ncurses                                       \
           pango                                         \
           tree-sitter                                   \
           zlib                                          \
           || die 'install_emacs: failed to install dependencies'

    # Now download emacs-git from AUR, build and install.
    _install_aur emacs-git

    # Compile tree-sitter modules.
    mkdir -p ~/local/ext
    (
        cd ~/local/ext || die
        git clone http://github.com/casouri/tree-sitter-module.git

        (
            cd tree-sitter-module || die
            ./batch.sh
            rm dist/libtree-sitter-c-sharp.so # fuck c-sharp
        )
    )
}

install_fonts() {
    sudo pacman -Sy --noconfirm --overwrite '*'          \
         nerd-fonts                                      \
         ttf-hack                                        \
         ttf-ubuntu-font-family                          \
         || die "install_fonts: failed"

    # Install fonts from AUR.
    _install_aur ttf-monaco
    _install_aur ttf-ms-fonts
    _install_aur ttf-courier-prime

    # Install dependencies and ttf-google-fonts-git from AUR.
    _install_aur ttf-signika
    _install_aur ttf-merriweather
    _install_aur ttf-merriweather-sans
    _install_aur ttf-oswald
    _install_aur ttf-quintessential
    _install_aur ttf-google-fonts-git
}

install_packages() {
    # It's nice if some packages get installed during the installation
    # phase:
    #
    # $ pacstrap /mnt dhcpcd git iwd sudo vi
    # - or, after arch-chroot -
    # $ pacman -S dhcpcd git iwd sudo vi

    # We'd need that.
    mkdir -p ~/.config

    # System
    #
    # NB: Installs https://archlinux.org/groups/x86_64/xorg-apps/
    sudo pacman -Sy --noconfirm --overwrite '*'          \
        alacritty                                        \
        aspell-en                                        \
        pulseaudio                                       \
        xorg-apps                                        \
        xorg-xclock                                      \
        || die 'install_packages: failed to install step 0'

    # System misc
    sudo pacman -Sy --noconfirm --overwrite '*'          \
        dhcpcd                                           \
        iw                                               \
        man                                              \
        man-pages                                        \
        openssh                                          \
        pacman-contrib                                   \
        tmux                                             \
        || die 'install_packages: failed to install step 1'

    # Programming.
    #
    # base-devel installs: binutils, gcc, gettext libtool pkgconf
    # https://archlinux.org/groups/x86_64/base-devel/
    sudo pacman -Sy --noconfirm --overwrite '*'          \
         base-devel                                      \
         clang                                           \
         cmake                                           \
         gdb                                             \
         valgrind                                        \
         || die 'install_packages: failed to install step 2'

    # Programming languages and package managers.
    sudo pacman -Sy --noconfirm --overwrite '*'          \
         go                                              \
         nodejs                                          \
         rustup                                          \
         || die 'install_packages: failed to install step 3'

    # Misc.
    sudo pacman -Sy --noconfirm --overwrite '*'          \
        btop                                             \
        direnv                                           \
        fasd                                             \
        htop                                             \
        imagemagick                                      \
        iotop                                            \
        jq                                               \
        keepass                                          \
        p7zip                                            \
        pavucontrol                                      \
        postgresql                                       \
        ripgrep                                          \
        shellcheck                                       \
        tree                                             \
        unzip                                            \
        vlc                                              \
        wget                                             \
        xclip                                            \
        || die 'install_packages: failed to install step 4'

    # Install base fonts.  Additional can be installed with the
    # install_fonts command.
    sudo pacman -Sy --noconfirm --overwrite '*'          \
        gnu-free-fonts                                   \
        ttf-cascadia-code                                \
        ttf-dejavu                                       \
        || die 'install_packages: failed to install step 5'

    # Misc GUI.
    sudo pacman -Sy --noconfirm --overwrite '*'          \
         firefox                                         \
         gimp                                            \
         transmission-gtk                                \
         || die 'install_packages: failed to install step 6'

    # Set Firefox as the default web browser.
    xdg-settings set default-web-browser firefox.desktop
}

install_rust() {
    # $ rustup default stable
    # info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
    # info: installing component 'cargo'
    # info: installing component 'clippy'
    # info: installing component 'rust-docs'
    # info: installing component 'rust-std'
    # info: installing component 'rustc'
    # info: installing component 'rustfmt'
    # stable-x86_64-unknown-linux-gnu installed

    # Here's a list of the components:
    # https://rust-lang.github.io/rustup/concepts/components.html
    #
    # Here's what's installed by default:
    # - cargo
    # - clippy
    # - rust-docs
    # - rust-stc
    # - rustc
    # - rustfmt
    #
    # Here's what's not installed:
    # - rust-analyzer
    # - rls
    # - miri
    # - rust-src
    # - rust-analysis
    # - rust-mingw
    # - llvm-tools-preview
    # - rust-dev
    #
    # Here's the list of all the valid proxy names for rustup:
    #   - rustc         [+]
    #   - rustdoc       [+ rust-docs]
    #   - cargo         [+]
    #   - rust-lldb
    #   - rust-gdb
    #   - rust-gdbgui
    #   - rls           [-]
    #   - cargo-clippy  [+ clippy]
    #   - clippy-driver [+ clippy}
    #   - cargo-miri    [+ cargo]
    #   - rustfmt       [+]
    #   - cargo-fmt     [+ cargo]

    rustup default stable
    rustup toolchain install stable --component rust-analyzer rust-src rust-analysis
}

install_x() {
    sudo pacman -Sy

    sudo pacman -S --noconfirm --overwrite '*' \
         i3 \
         xorg \
         xorg-xinit \
         xterm
}

install_sway() {

    sudo pacman -S --noconfirm --overwrite '*' --asdeps \
        bemenu                                          \
        dmenu                                           \
        i3status                                        \
        mako                                            \
        slurp                                           \
        swaybg                                          \
        swayidle                                        \
        swaylock                                        \
        wallutils                                       \
        waybar                                          \
        wayland                                         \
        xorg-xwayland

    sudo pacman -S --noconfirm --overwrite '*'          \
        brightnessctl                                   \
        foot                                            \
        wmenu                                           \
        grim                                            \
        sway

    # TODO: Install polkit?

    # These two are needed for my fancy swaybar status.sh.
    sudo pacman -S --noconfirm --overwrite '*' --asdeps \
        acpi noto-fonts-emoji

}

install_tools() {
    sudo pacman -Sy

    # TODO: Install golangci-lint?
    # TODO: Install multisol from cargo?

    sudo pacman -Sy --noconfirm  --overwrite '*' \
        bash-language-server                     \
        delve                                    \
        gopls                                    \
        haskell-language-server                  \
        jedi-language-server                     \
        npm                                      \
        pyright                                  \
        python-lsp-server                        \
        texlab                                   \
        typescript-language-server               \
        yaml-language-server                     \
        yarn
}

if [ $# -eq 0 ] || [ "$1" = "help" ] ; then
    usage
else
    for arg in "$@" ; do
        if [[ "${COMMANDS[*]}" =~ $arg ]]; then
            $arg
        else
            die "unrecognized command:" "$arg"
        fi
    done
fi
