#!/bin/bash

ROOT=$(readlink -f $(dirname ${BASH_SOURCE[0]}))
COMMANDS=( config_alacritty
           config_bash
           config_emacs
           config_sway
           config_sway_startup
           install_packages
           install_sway
           install_x )

out() { printf "$1 $2\n" "${@:3}"; }
error() { out "==> ERROR:" "$@"; } >&2
die() { error "$@"; exit 1; }

usage() {
    out "Usage: $0 <command>..."
    out
    out "Commands:"
    for c in ${COMMANDS[@]} ; do
        out '  ' $c
    done
}

config_alacritty() {
    rm -rf ~/.config/alacritty
    mkdir -p ~/.config/alacritty
    cp $ROOT/alacritty/alacritty.yml ~/.config/alacritty/
}

config_bash() {
    echo "source $ROOT/shell/aliases.sh" >> ~/.bashrc
}

config_emacs() {
    PATH="$ROOT"/emacs/y-init.el
    echo "(load \"$PATH\")"
}

config_sway() {
    SWAY=$HOME/.config/sway
    TMP=/tmp/c8bd855267bd

    # First, copy existing conf files
    rm -rf $TMP
    mkdir $TMP
    cp $SWAY/*.conf $TMP

    # Now recreate the sway directory with an original sway config +
    # inclusion of conf files
    rm -rf $SWAY
    mkdir -p $SWAY
    cp -f /etc/sway/config $SWAY
    echo "include $HOME/.config/sway/*.conf" >> $SWAY/config

    # Copy over existing conf files
    cp -t $SWAY $TMP/*

    # Copy predefined conf files
    cp -t $SWAY $ROOT/sway/*.conf

    # Generate brand new input.conf
    $ROOT/sway/gen.py > $SWAY/input.conf
}

config_sway_startup() {
    cat >>~/.bash_profile <<EOF

if [[ -z \$DISPLAY ]] && [[ \$(tty) = /dev/tty1 ]]; then
    XKB_DEFAULT_LAYOUT=us exec sway
fi
EOF
}

install_packages() {

    pacman -Sy --confirm aspell-en base-devel clang cmake dhcpcd emacs \
           firefox gdb git git gnu-free-fonts pacman-contrib pavucontrol \
           pkgconf qt5-base sudo the_silver_searcher tree ttf-cascadia-code \
           ttf-dejavu ttf-hack ttf-ubuntu-font-family valgrind wpa_supplicant

}

install_sway() {

    pacman -Sy --confirm alacritty dmenu grim i3status mako slurp sway \
           swayidle swaylock wallutils waybar wayland

}

install_x() {
    pacman -Sy i3 xorg xorg-xclock xorg-xinit xterm
}

# TODO: AUR packages: ttf-monaco ttf-google-fonts-git ttf-courier-prime
# ttf-ms-fonts

if [ $# -eq 0 ] || [ $1 = "help" ] ; then
    usage
else
    for arg in $@ ; do
        if [[ "${COMMANDS[*]}" =~ "$arg" ]]; then
            $arg
        else
            die "unrecognized command: %s" "$arg"
        fi
    done
fi
