#!/usr/bin/env python

import json
import sys


def main():
    out = sys.argv[1] if len(sys.argv) >= 2 else 'output.json'
    if not out.endswith('.json'):
        out = f'{out}.json'     # TODO: Use pathlib?
    obj = json.load(sys.stdin)
    with open(out, 'w', encoding='ascii') as f:
        json.dump(obj, f, indent=4)


if __name__ == '__main__':
    main()
