#!/usr/bin/env bash

INTERFACE=$(ip link | grep -Poe '^\d+:\s+w[^:]+' | sed 's/^[[:digit:]]\+:[[:space:]]\+//')
echo "INTERFACE=$INTERFACE"

# sudo rm /dev/rfkill

sudo ip link set wlo1 down
sudo ip link set wlo1 up
sudo iw dev "$INTERFACE" connect "$1"
