#!/bin/bash

switchxkbmap () {
    setxkbmap -print | grep -Pe 'xkb_symbols.*?\+us\+' > /dev/null
    if [ $? = 0 ]
    then
        # current layout is us, switch to bulgarian
        setxkbmap -layout bg -variant bas_phonetic -option ctrl:nocaps
    else
        # switch to us
        setxkbmap us -option ctrl:nocaps
    fi

    # http://emacswiki.org/emacs/MovingTheCtrlKey
    # setxkbmap -option ctrl:nocaps       # Make Caps Lock a Control key
}

switchxkbmap

# Used in my Emacs config to start M-x
xmodmap -e "keycode 62 = F13"
