# -*- mode: Shell-script -*-
# A lot of thanks to https://github.com/bitprophet/dotfiles/

# Colors
alias grep='grep --color=auto'
alias ls='ls --color=auto'

# Editing
alias e='emacsclient -c'

# Sys
alias res='sudo reboot'
alias bye='sudo shutdown -h 0'

# Git
alias gl="git log --pretty=tformat:'%h %Cblue%cr%Creset %cn %Cgreen%s%Creset'"
alias glg="git log --graph --pretty=format:'%Cblue%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
alias gst='git status'
alias gpull='git pull origin master'
alias gpush='git push origin master'

# Navigation
alias ....='cd ../../..'
alias ...='cd ../../'
alias ..='cd ..'
alias l='ls'
alias la='ls -a'
alias lal='ls -al'
alias ll='ls -l'

# Arch
alias upgrade='sudo pacman -Syu --noconfirm'

# Other
alias t='tree -Ca -I ".git"'
